### PR TITLE
Add travis configuration file

### PR DESCRIPTION
**Pull request by szabgab**
Please also enable the repository at https://travis-ci.org/

### CODE REVIEW

**Comment by jonathanstowe** [comment]
Hi,
thanks.

I'm not going to merge this until I can find out how to install the dependency libsamplerate.

**Comment by szabgab** [comment]
I think you can just add

`sudo apt-get -y install libsamplerate`

and you'll also need to set

sudo: true

See here: http://docs.travis-ci.com/user/installing-dependencies/

**Comment by jonathanstowe** [comment]
Yeah just looking at this now :) Cheers.

**Comment by jonathanstowe** [comment]
Cheers, all good, let's see how this goes.

**Comment by jonathanstowe** [comment]
All good https://travis-ci.org/jonathanstowe/Audio-Convert-Samplerate

**Pull request merged**
